# This compose file will spin up the docker environment required to use the database gui:

version: '3.8'
services :
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: brewed
      POSTGRES_PASSWORD: awakening
      POSTGRES_DB: group_project
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080
